name: 'terraform-plan-approve-apply' # 'Hello World'
description: 'Greet someone'
inputs:
  working-directory:
    description: 'Working directory for this action'
    required: false
    default: '.'
  who-to-greet:  # ID of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - name: Hello
      run: echo Hello ${{ inputs.who-to-greet }}. ${{ inputs.working-directory }}
      shell: bash
    - name: Random Number Generator
      id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - name: Goodbye Script
      run: ${{ github.action_path }}/goodbye.sh
      shell: bash
    - name: Terraform Format
      id: fmt
      run: echo terraform fmt -check
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Terraform Init
      id: init
      run: echo terraform init -input=false
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Terraform Validate
      id: validate
      run: echo terraform validate -no-color
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Terraform Plan
      id: plan
#      if: github.event_name == 'pull_request'
      run: echo terraform plan -no-color -input=false
      shell: bash
      working-directory: ${{ inputs.working-directory }}
#      continue-on-error: true
